server:
  port: 8081

spring:
  flyway:
    enabled: true

  datasource:
    url: jdbc:postgresql://host.docker.internal:5433/postgres
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  springdoc:
    api-docs:
      path: /api-docs
    swagger-ui:
      path: /swagger-ui.html
      enabled: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: azimochilov29@gmail.com
    password: "ovju mahs dzom kgis"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

security:
  jwt:
    secret-key: secret

