server:
  port: ${SERVER_PORT}
spring:
  flyway:
    enabled: ${MIGRATION_ENABLE}

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
    show-sql: ${SPRING_JPA_SHOW_SQL}
    database: ${SPRING_JPA_DATABASE}
    database-platform: ${SPRING_JPA_DATABASE_PLATFORM}
  springdoc:
    api-docs:
      path: ${SPRING_SPRINGDOC_API_DOCS_PATH}
    swagger-ui:
      path: ${SPRING_SPRINGDOC_SWAGGER_UI_PATH}
      enabled: ${SPRING_SPRINGDOC_SWAGGER_UI_ENABLED}

  mail:
    host: ${SPRING_MAIL_HOST}
    port: ${SPRING_MAIL_PORT}
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: ${SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH}
          starttls:
            enable: ${SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE}

security:
  jwt:
    secret-key: ${SECURITY_JWT_SECRET_KEY}

